---
title: EmocionLUZ
author: Isaí Aragón
email: isai@emocionluz.com
description: EmocionLUZ. Iluminación y Sistemas de Control Inteligente. Creamos espacios
  con Emoción a través de la LUZ.
baseurl: ''
url: emocionluz.com
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-sitemap
- jekyll-feed
- jekyll-menus
