---
title: EmocionLUZ
author: Isaí Aragón
email: isai@emocionluz.com
description: EmocionLUZ, iluminación y sistemas de control inteligente. Creamos espacios
  con Emoción a través de la LUZ.
baseurl: "/ubuild-jekyll"
url: emocionluz,com
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
